public class CustomVisionPredictionClient :
Microsoft.Rest.ServiceClient<Microsoft.Azure.CognitiveServices.Vision.CustomVision.Prediction.CustomVisionPredictionClient>,
IDisposable, Microsoft.Azure.CognitiveServices.Vision.CustomVision.Prediction.ICustomVisionPredictionClient